version: '2'
services:
  hrp_sq:
    depends_on:
      - db_sq
    image: kavinlee0121/odoo:13.0
    volumes:
      - ./data:/var/lib/odoo
      - ./code:/opt/odoo
    ports:
      - "8071:8069"
      - "8074:8072"
    environment:
      ODOO_CONNECTOR_CHANNELS: root:1,root.highcap:1
    command:
      - /opt/odoo/odoo/odoo-bin
      - --config=/opt/odoo/hrp-server.conf
    restart: unless-stopped

  db_sq:
    image: postgres:12.0
    ports:
      - "5433:5432"
    volumes:
      - ./db_data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
      - ./nginx/certs:/etc/nginx/certs
      - ./data:/usr/share/nginx/html
    depends_on:
      - hrp_sq
    restart: always
